version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
      FLASK_ENV: development
      SQLALCHEMY_WARN_20: 1
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
      FRESHDESK_API_KEY: BKLJtkXkZ2dA8W4gaW
      FRESHDESK_DOMAIN: stiegler.freshdesk.com
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - loan-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loan-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - loan-network
    volumes:
      - ./backend/config/pgadmin_servers.json:/pgadmin4/servers.json

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_FRESHDESK_URL: stiegler.freshdesk.com
    networks:
      - loan-network

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile.scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    volumes:
      - ./backend:/app
      - etl_logs:/var/log
    networks:
      - loan-network

volumes:
  pgdata:
  etl_logs:

networks:
  loan-network:
    driver: bridge
